FROM node:alpine

WORKDIR /app

COPY ./package.json ./

RUN npm i

COPY . ./

ENV MONGO_URL=${MONGO_URL}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
ENV TOKEN_GENERATOR=${TOKEN_GENERATOR}
ENV CONSOLE_SIGNIN=${CONSOLE_SIGNIN}
ENV AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
ENV AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
ENV STRIPE_PRIVATE_KEY=${STRIPE_PRIVATE_KEY}
ENV PORT=3000

CMD ["npm", "run", "dev"]
